version: '3.6'

services:

  proxy:
    build: ./front/
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./data:/data"

  back:
    build: ./back/
    volumes:
      - "./data:/app/data"
