version: '3.6'

services:

  proxy:
    build: ./front/
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./data:/data/"
      - "./front/dist:/front_files"
#    environment:
#      - BACK_URI=https://localhost:3030

  back:
    build: ./back/
    volumes:
      - "./data:/app/data"

  watcher:
    build: 
      context: ./front/
      target: builder
    volumes:
      - "./data:/data/"
      - "./front/src:/app/src"
      - "./front/dist:/app/dist"
    command: "yarn build --watch --no-clean"