version: '3.6'

services:

  proxy:
    build: ./front/
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./data:/data/"
    restart: unless-stopped

  back:
    build: ./back/
    volumes:
      - "./data:/app/data"
#      - "/etc/letsencrypt/live/docker.synergee.com/server.cert:/ssl/server.cert"
#      - "/etc/letsencrypt/live/docker.synergee.com/server.key:/ssl/server.key"
    restart: unless-stoppe<d
