version: '3.6'

services:

  proxy:
    build: ./front/
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./data:/data/"
      - "./deploy/certbot/www:/var/www/certbot"
      - "./deploy/certbot/conf/live/app.bakuanimation.com/:/ssl/"
    restart: unless-stopped

  back:
    build: ./back/
    volumes:
      - "./data:/app/data"
    restart: unless-stopped
