
tls:
  stores:
    default:
    
http:

  middlewares:
    redirect:
      redirectScheme:
        scheme: https
    compress:
      compress:
        excludedContentTypes:
          - image/jpeg
          - image/jpg
          - image/png