micronaut:
  application:
    name: baku
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/**"
        paths: "classpath:dist"
netty:
  responses:
    file:
      cache-seconds: 604800

