micronaut:
  application:
    name: baku
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/**"
        paths: "fb:dist"
  executors:
    io:
      type: fixed
      nThreads: 75
netty:
  responses:
    file:
      cache-seconds: 604800

